version: '3.3'
services:
  node:
    image: node:20.10-alpine
    environment:
      - NITRO_PORT=3333
    ports:
      - 3333:3333
    working_dir: /www
    entrypoint: node .output/server/index.mjs
    volumes:
      - ./:/www