version: '3.3'
services:
  node:
    image: node:20.10-alpine
    environment:
      - API_URL=https://your-new-backend-url.railway.app
    ports:
      - "3000:3000"
    working_dir: /www
    entrypoint: node .output/server/index.mjs
    volumes:
      - ./:/www

